version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acsys
    networks:
      - freecodecamp
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  freecodecamp:

volumes:
  postgres_data: